"""multi-tenant model: tenants, users, agents, commands

Revision ID: 513e5302fa0d
Revises: 8507f9a69bf4
Create Date: 2026-07-26 19:18:05.608037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '513e5302fa0d'
down_revision: Union[str, Sequence[str], None] = '8507f9a69bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sa.Enum('aws', 'azure', 'gcp', 'onprem', name='agentenvironment'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'online', 'offline', 'revoked', name='agentstatus'), nullable=False),
    sa.Column('enrollment_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('last_reported_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_token')
    )
    op.create_index(op.f('ix_agent_tenant_id'), 'agent', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'tenant_admin', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'dispatched', 'success', 'failure', name='commandstatus'), nullable=False),
    sa.Column('result_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_agent_id'), 'command', ['agent_id'], unique=False)
    op.create_index(op.f('ix_command_tenant_id'), 'command', ['tenant_id'], unique=False)
    op.add_column('auditevent', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_auditevent_tenant_id'), 'auditevent', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'auditevent', 'tenant', ['tenant_id'], ['id'])
    op.add_column('connector', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_connector_name'), table_name='connector')
    op.create_index(op.f('ix_connector_name'), 'connector', ['name'], unique=False)
    op.create_index(op.f('ix_connector_tenant_id'), 'connector', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'connector', 'tenant', ['tenant_id'], ['id'])
    op.add_column('subscriber', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_subscriber_tenant_id'), 'subscriber', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'subscriber', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriber', type_='foreignkey')
    op.drop_index(op.f('ix_subscriber_tenant_id'), table_name='subscriber')
    op.drop_column('subscriber', 'tenant_id')
    op.drop_constraint(None, 'connector', type_='foreignkey')
    op.drop_index(op.f('ix_connector_tenant_id'), table_name='connector')
    op.drop_index(op.f('ix_connector_name'), table_name='connector')
    op.create_index(op.f('ix_connector_name'), 'connector', ['name'], unique=1)
    op.drop_column('connector', 'tenant_id')
    op.drop_constraint(None, 'auditevent', type_='foreignkey')
    op.drop_index(op.f('ix_auditevent_tenant_id'), table_name='auditevent')
    op.drop_column('auditevent', 'tenant_id')
    op.drop_index(op.f('ix_command_tenant_id'), table_name='command')
    op.drop_index(op.f('ix_command_agent_id'), table_name='command')
    op.drop_table('command')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_agent_tenant_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
