"""add metricssnapshot table

Revision ID: 6bd4cd0bf257
Revises: 80df4fbec55b
Create Date: 2026-08-15 07:54:22.957713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '6bd4cd0bf257'
down_revision: Union[str, Sequence[str], None] = '80df4fbec55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricssnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('containers_running', sa.Integer(), nullable=False),
    sa.Column('containers_total', sa.Integer(), nullable=False),
    sa.Column('rows_trade', sa.Integer(), nullable=False),
    sa.Column('rows_risk', sa.Integer(), nullable=False),
    sa.Column('shards_healthy', sa.Integer(), nullable=False),
    sa.Column('shards_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricssnapshot_timestamp'), 'metricssnapshot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metricssnapshot_timestamp'), table_name='metricssnapshot')
    op.drop_table('metricssnapshot')
    # ### end Alembic commands ###
