"""add sso, ldap, bot, infra_profile tables and userrole roles

Revision ID: 80df4fbec55b
Revises: e5f6a7b8c9d0
Create Date: 2026-08-14 22:38:50.807255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '80df4fbec55b'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbols_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('paper_capital', sa.Float(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botconfig_tenant_id'), 'botconfig', ['tenant_id'], unique=True)
    op.create_table('botlogentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botlogentry_tenant_id'), 'botlogentry', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_botlogentry_timestamp'), 'botlogentry', ['timestamp'], unique=False)
    op.create_table('infraprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infraprofile_name'), 'infraprofile', ['name'], unique=False)
    op.create_index(op.f('ix_infraprofile_tenant_id'), 'infraprofile', ['tenant_id'], unique=False)
    op.create_table('querycostevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('elapsed_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_querycostevent_tenant_id'), 'querycostevent', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_querycostevent_timestamp'), 'querycostevent', ['timestamp'], unique=False)
    op.create_table('tenantidp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_role_map', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_role', sa.Enum('platform_admin', 'tenant_admin', 'functional_user', 'quant_analyst', name='userrole'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantidp_tenant_id'), 'tenantidp', ['tenant_id'], unique=True)
    op.create_table('tenantldap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('server_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_start_tls', sa.Boolean(), nullable=False),
    sa.Column('bind_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bind_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bind_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_search_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bind_dn_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attr_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attr_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_role_map', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_role', sa.Enum('platform_admin', 'tenant_admin', 'functional_user', 'quant_analyst', name='userrole'), nullable=False),
    sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantldap_tenant_id'), 'tenantldap', ['tenant_id'], unique=True)
    op.create_table('botposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botposition_symbol'), 'botposition', ['symbol'], unique=False)
    op.create_index(op.f('ix_botposition_tenant_id'), 'botposition', ['tenant_id'], unique=False)
    # batch_alter_table - SQLite has no ALTER TABLE ... ALTER COLUMN ... TYPE
    # (confirmed live: the plain op.alter_column autogenerate wrote failed
    # outright with a syntax error on SQLite), and needs the copy-and-move
    # strategy for this whole group of column changes on 'user'. server_
    # default='local' on auth_provider (not in the autogenerated version) so
    # existing rows in a populated table get backfilled correctly instead of
    # failing on a NOT NULL column with nothing to put in it.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=14),
                   type_=sa.Enum('platform_admin', 'tenant_admin', 'functional_user', 'quant_analyst', name='userrole'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.Enum('platform_admin', 'tenant_admin', 'functional_user', 'quant_analyst', name='userrole'),
                   type_=sa.VARCHAR(length=14),
                   existing_nullable=False)
        batch_op.drop_column('external_id')
        batch_op.drop_column('auth_provider')
    op.drop_index(op.f('ix_botposition_tenant_id'), table_name='botposition')
    op.drop_index(op.f('ix_botposition_symbol'), table_name='botposition')
    op.drop_table('botposition')
    op.drop_index(op.f('ix_tenantldap_tenant_id'), table_name='tenantldap')
    op.drop_table('tenantldap')
    op.drop_index(op.f('ix_tenantidp_tenant_id'), table_name='tenantidp')
    op.drop_table('tenantidp')
    op.drop_index(op.f('ix_querycostevent_timestamp'), table_name='querycostevent')
    op.drop_index(op.f('ix_querycostevent_tenant_id'), table_name='querycostevent')
    op.drop_table('querycostevent')
    op.drop_index(op.f('ix_infraprofile_tenant_id'), table_name='infraprofile')
    op.drop_index(op.f('ix_infraprofile_name'), table_name='infraprofile')
    op.drop_table('infraprofile')
    op.drop_index(op.f('ix_botlogentry_timestamp'), table_name='botlogentry')
    op.drop_index(op.f('ix_botlogentry_tenant_id'), table_name='botlogentry')
    op.drop_table('botlogentry')
    op.drop_index(op.f('ix_botconfig_tenant_id'), table_name='botconfig')
    op.drop_table('botconfig')
    # ### end Alembic commands ###
