"""add feedhandlerinstance table

Revision ID: 8d6b6de2e33d
Revises: f575a499c165
Create Date: 2026-08-15 19:22:03.052405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '8d6b6de2e33d'
down_revision: Union[str, Sequence[str], None] = 'f575a499c165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedhandlerinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secrets_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedhandlerinstance_provider'), 'feedhandlerinstance', ['provider'], unique=False)
    op.create_index(op.f('ix_feedhandlerinstance_tenant_id'), 'feedhandlerinstance', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedhandlerinstance_tenant_id'), table_name='feedhandlerinstance')
    op.drop_index(op.f('ix_feedhandlerinstance_provider'), table_name='feedhandlerinstance')
    op.drop_table('feedhandlerinstance')
    # ### end Alembic commands ###
