"""add feedhandlerinstance.tickhouse_id

Revision ID: 9de844ed5a3a
Revises: 8d6b6de2e33d
Create Date: 2026-08-15 19:43:36.825930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '9de844ed5a3a'
down_revision: Union[str, Sequence[str], None] = '8d6b6de2e33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # batch mode: SQLite can't ALTER a table to add a foreign key constraint
    # directly (NotImplementedError) - same fix as 513e5302fa0d's own
    # auditevent/connector/subscriber FK additions. Batch mode also requires
    # an explicitly named constraint (None isn't accepted).
    with op.batch_alter_table('feedhandlerinstance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickhouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_feedhandlerinstance_tickhouse_id'), ['tickhouse_id'], unique=False)
        batch_op.create_foreign_key('fk_feedhandlerinstance_tickhouse_id_tickhouse', 'tickhouse', ['tickhouse_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('feedhandlerinstance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedhandlerinstance_tickhouse_id_tickhouse', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feedhandlerinstance_tickhouse_id'))
        batch_op.drop_column('tickhouse_id')
