"""add command.payload for provisioning specs

Revision ID: a1b2c3d4e5f6
Revises: 513e5302fa0d
Create Date: 2026-08-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '513e5302fa0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the payload column that carries richer command specs (the desired
    topology for `provision` commands). Existing rows default to '{}'."""
    op.add_column(
        'command',
        sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='{}'),
    )


def downgrade() -> None:
    op.drop_column('command', 'payload')
