"""add tradingviewwebhook table

Revision ID: a3f8c1d2e9b4
Revises: 9de844ed5a3a
Create Date: 2026-08-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'a3f8c1d2e9b4'
down_revision: Union[str, Sequence[str], None] = '9de844ed5a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('tradingviewwebhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_symbols_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_qty', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradingviewwebhook_tenant_id'), 'tradingviewwebhook', ['tenant_id'], unique=True)
    op.create_index(op.f('ix_tradingviewwebhook_token'), 'tradingviewwebhook', ['token'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_tradingviewwebhook_token'), table_name='tradingviewwebhook')
    op.drop_index(op.f('ix_tradingviewwebhook_tenant_id'), table_name='tradingviewwebhook')
    op.drop_table('tradingviewwebhook')
