"""add cloudprovisionrun table

Revision ID: b7e4f2a1c6d3
Revises: a3f8c1d2e9b4
Create Date: 2026-08-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'b7e4f2a1c6d3'
down_revision: Union[str, Sequence[str], None] = 'a3f8c1d2e9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('cloudprovisionrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_tail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terraform_outputs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tickhouse_id', sa.Integer(), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tickhouse_id'], ['tickhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudprovisionrun_tenant_id'), 'cloudprovisionrun', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cloudprovisionrun_name'), 'cloudprovisionrun', ['name'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_cloudprovisionrun_name'), table_name='cloudprovisionrun')
    op.drop_index(op.f('ix_cloudprovisionrun_tenant_id'), table_name='cloudprovisionrun')
    op.drop_table('cloudprovisionrun')
