"""add dailypnlbaseline table

Revision ID: eb6e8f95b7dc
Revises: 6bd4cd0bf257
Create Date: 2026-08-15 07:59:50.217438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: SQLModel's AutoString type shows up in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'eb6e8f95b7dc'
down_revision: Union[str, Sequence[str], None] = '6bd4cd0bf257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailypnlbaseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('baseline_realized_pnl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailypnlbaseline_tenant_id'), 'dailypnlbaseline', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dailypnlbaseline_trading_date'), 'dailypnlbaseline', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailypnlbaseline_trading_date'), table_name='dailypnlbaseline')
    op.drop_index(op.f('ix_dailypnlbaseline_tenant_id'), table_name='dailypnlbaseline')
    op.drop_table('dailypnlbaseline')
    # ### end Alembic commands ###
