// MoldUdp64Simulator.hpp - generates synthetic MoldUDP64-framed ITCH
// packets (System Event, Stock Directory, Add Order, Trade, Cancel,
// Delete) for a configurable set of symbols. This is the "dummy data"
// half of the simulation workflow requested for testing before real
// exchange entitlements are connected: the generated bytes flow through
// the EXACT SAME MoldUdp64Decoder -> NasdaqItchVenueAdapter -> KdbPublisher
// pipeline a real feed would, via InProcessTransport - nothing downstream
// of the transport can tell the difference between this and a real feed.
//
// Can optionally drop a configured fraction of packets (dropEveryNth) to
// exercise SequenceTracker/RecoveryManager's gap-detection path under
// test, matching design section 13's "test sequence gaps... without
// connecting to a live exchange."
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include "../transport/InProcessTransport.hpp"

namespace fh::sim {

struct MoldUdp64SimConfig {
    std::string session = "SIM-SESSION";
    std::vector<std::string> symbols = {"AAPL", "MSFT"};
    uint32_t tradesPerSymbol = 10;
    uint32_t dropEveryNth = 0; // 0 = never drop; e.g. 7 = silently skip sending every 7th packet
    double basePrice = 100.0;
};

class MoldUdp64Simulator {
public:
    explicit MoldUdp64Simulator(MoldUdp64SimConfig cfg) : cfg_(std::move(cfg)) {}

    // Runs the whole synthetic session (system event, stock directory per
    // symbol, then interleaved add-order/trade/cancel/delete messages) into
    // `transport`, one MoldUDP64 packet per call to feed(). Returns the
    // number of packets actually sent (excludes any dropped for gap testing).
    size_t run(InProcessTransport& transport);

private:
    MoldUdp64SimConfig cfg_;
    uint64_t sequence_ = 1;

    std::vector<uint8_t> buildPacket(const std::vector<std::vector<uint8_t>>& innerMessages);
    bool sendPacket(InProcessTransport& transport, const std::vector<uint8_t>& innerMessage, uint32_t& packetCount);
};

} // namespace fh::sim
